modLoader="javafml"
loaderVersion="[47,)"
license="Apache License 2.0"
issueTrackerURL="https://github.com/lnsanes/itemban/issues"

[[mods]]
modId="itemban"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/lnsanes/itemban"
#logoFile="logo.png"
authors="${mod_author}"
description="${mod_description}"

[[dependencies.itemban]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.itemban]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.itemban]]
    modId="ae2"
    mandatory=false
    versionRange="[15.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.itemban]]
    modId="sophisticatedbackpacks"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.itemban]]
    modId="create"
    mandatory=false
    versionRange="[0.5.1,)"
    ordering="NONE"
    side="BOTH"
