modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
#issueTrackerURL="https://github.com/lnsanes/itemban/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_author}"
description="${mod_description}"
displayTest="IGNORE_ALL_VERSION"
#logoFile="logo.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
