# Minecraft and Forge versions
minecraft_version=1.21.1
forge_version=52.1.0
mod_version=1.0.8
mod_name=ItemBan
mod_author=lnsanes
mod_description=Server-side mod that blacklists items, removes recipes, and auto-deletes them from inventories & containers. Compatible with AE2, Create, Sophisticated Backpacks & more. OP/creative exempt. Commands: /itemban add/remove/list/reload

org.gradle.jvmargs=-Xmx3G -Djavax.net.ssl.trustStoreType=Windows-ROOT
net.minecraftforge.gradle.check.certs=false
org.gradle.daemon=false
