# Project
group=com.itemban
mod_id=itemban
mod_name=ItemBan
mod_author=lnsanes
mod_license=Apache License 2.0
mod_version=1.0.8
mod_description=Server-side blacklist for items & blocks (NBT/Data Components), auto-removal, announcements, optional auto-ban, audit logs.

# Minecraft / NeoForge (override via -Pmc=1.21 or -Pmc=1.21.1)
mc=26.1.2
minecraft_version=26.1.2
neo_version=26.1.2.95
neogradle_version=7.1.38
minecraft_version_range=[26.1.2,26.2)
neoforge_version_range=[26.1.2.0,26.2)

# Gradle
org.gradle.jvmargs=-Xmx3G -Djavax.net.ssl.trustStoreType=Windows-ROOT
systemProp.javax.net.ssl.trustStoreType=Windows-ROOT
org.gradle.daemon=false
org.gradle.parallel=false
